#!/usr/bin/env bash

ask () {
  printf "\n"
  read -p "$1 " -r
}

info () {
  printf "\n*** $1 ***\n"
}

info 'Installing Homebrew'
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  brew update

info 'Installing Homebrew packages'
  brew tap heroku/brew && brew install git heroku Schniz/tap/fnm vim yarn zsh-syntax-highlighting

ask 'Which Node version do you want to install?'
  fnm install "$REPLY"
  fnm default "$REPLY"

info 'Installing Pure prompt'
  npm install -g pure-prompt

info 'Symlinking dotfiles'
  sh symlink

info 'Install vim-plug'
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

info 'Done!'
