#!/usr/bin/env bash

ask () {
  printf "\n"
  read -p "$1 " -r
}

info () {
  printf "\n*** $1 ***\n"
}

info 'Installing Homebrew'
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  brew update

info 'Installing Homebrew packages'
  brew install git heroku-toolbelt vim zsh zsh-syntax-highlighting
  brew install yarn --without-node

info 'Setting zsh as default shell'
  grep -q -F '/usr/local/bin/zsh' /etc/shells || sudo sh -c 'echo /usr/local/bin/zsh >> /etc/shells'
  chsh -s /usr/local/bin/zsh

info 'Setting up git'
  git config --global user.name 'Richard Käll'
  git config --global user.email 'richard.kall@me.com'
  git config --global color.ui true

ask 'Which nvm version do you want to install?'
  curl -o- "https://raw.githubusercontent.com/creationix/nvm/v$REPLY/install.sh" | zsh
  export NVM_DIR=$HOME/.nvm
  source $NVM_DIR/nvm.sh

ask 'Which Node version do you want to install?'
  nvm install "$REPLY"
  nvm alias default "$REPLY"

info 'Installing Pure prompt'
  npm install -g pure-prompt

info 'Symlinking dotfiles'
  sh symlink

info 'Install vim-plug'
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

info 'Done! Please logout for changes to take effect.'
